# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: php-ews
#email: hemangsk@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>php-ews</h1>PHP Exchange Web Services library."

#google analytics
google:
    tracking-id: "UA-3412924-3" #paste your tracking id here

baseurl: "/php-ews" # the subpath of your site, e.g. /blog
url: "http://jamesarmes.com" # the base hostname & protocol for your site
twitter_username: jamesiarmes
github_username:  jamesiarmes

# Build settings
markdown: kramdown

collections:
  example:
    output: true
    permalink: /doc/:categories/examples/:title.html

defaults:
  -
    scope:
      path: ""
      type: "example"
    values:
      layout: "doc"
